version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1319
  
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  cleanUrls: false
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
