runMode: compare-release-with-baseline
releaseDir: release-v2
baselineDir: golden-copy
projects: [insurance-policy-docs, test-docs]
includeDocs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
  - project: insurance-policy-docs
    doc: Acme Inc - Health Plus Policy.pdf
  - project: insurance-policy-docs    
    doc: Acme Inc - Burglary Insurance Policy (Commercial) Add-On Covers.pdf
excludeDocs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
specialDocConfigs:
  - project: insurance-policy-docs
    doc: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover.pdf
    includePages: []
    excludePages: []
  - project: insurance-policy-docs
    doc: Acme Inc - Health Plus Policy.pdf
    includePages: []
    excludePages: [4, 7]
  - project: insurance-policy-docs
    doc: Acme Inc - Burglary Insurance Policy (Commercial) Add-On Covers.pdf
    includePages: []
    excludePages: [2]
