- pdfDocId: DOC-0001
  projectFolder: insurance-policy-docs
  pdfFileName: Acme Inc - Private Car Stand Alone Own Damage Add-On Cover
  pdfPageCount: 20
  includePages: []
  excludePages: []
  runMode: compare-release-with-baseline
  baselineDir: golden-copy
  releaseDir: release-v2
- pdfDocId: DOC-0002
  projectFolder: insurance-policy-docs
  pdfFileName: Acme Inc - Health Plus Policy
  pdfPageCount: 52
  includePages: [1, 2, 3, 5, 7, 8, 12, 14, 15, 17, 25, 28, 30]
  excludePages: []
  runMode: compare-release-with-baseline
  baselineDir: golden-copy
  releaseDir: release-v2
- pdfDocId: DOC-0003
  projectFolder: insurance-policy-docs
  pdfFileName: Acme Inc - Burglary Insurance Policy (Commercial) Add-On Covers
  pdfPageCount: 4
  includePages: []
  excludePages: [2]
  runMode: compare-release-with-baseline
  baselineDir: golden-copy
  releaseDir: release-v2